### ISSUE TITLE
Not abap cloud compatible

### ISSUE THREAD

**Issue by ArneVanH** [hhelibeb/abap-data-validator#21]
Hi,

We pulled this repo as it was marked as cloud compatible on dotabap.org, however concluded that it is in fact not (no longer?) cloud compatible.

With the following changes we were able to get a working version:
- replace some data elements with cloud released data elements
- replace retrieval code of interface implementation list with: 
           classes_list = xco_cp_abap=>interface( 'ZIF_ADV_CHECK' )->implementations->all->get_names( ).
- find cloud enabled apis for date and time plausibility (we have, for the moment, simply deactivated these checks...)
- http check -> we completely removed this check because "if_http_entity" and related objects are not released, so a complete rework is probably needed..

In either case, we got it up and running relatively quickly - so thanks!

**Comment by hhelibeb** [comment]
Hi @ArneVanH, I'm very glad to hear that someone else is using the repo besides myself.😄

Thank you for providing details regarding compatibility. I'm not sure how dotabap determines the "cloud ready" flag. I will add the information you've provided to README , and will look into how to improve the code accordingly.

In the meantime, if you're interested, feel free to fork this repo and replace the files with your cloud-compatible version. I believe this would be helpful for developers who are using ABAP Cloud.

**Comment by ArneVanH** [comment]
Created a pull request after making changes for cloud compatibility.
Couldn't test if the cloud-APIs exist on non-cloud systems -> so maybe not an interesting pull to accept if not..
